// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pykpouvalnjkmnswsqzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5a3BvdXZhbG5qa21uc3dzcXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3ODM4NzMsImV4cCI6MjA1MzM1OTg3M30.-XZo0Ldjdld32hMSEr5tzpW30RmE-XlnUYlf1iTSWiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);